name: deploy-prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: |
          ssh -i ~/.ssh/deploy_key_prod ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} "
          docker compose down || true
          docker compose up -d --build
          "
